services:
  db:
    image: postgres:13.2-alpine
    container_name: db_redmine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - database:/var/lib/postgresql/data

  redmine:
    image: redmine:4.1-alpine
    restart: unless-stopped
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_PASSWORD=example
    ports:
      - "9999:3000"
    volumes:
      - files:/usr/src/redmine/files
    depends_on:
      - db

  adminer:
    image: adminer:4
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN=galkaev
      # jeśli db nie nazywałby się "db", wtedy:
      # - ADMINER_DEFAULT_SERVER=db
    ports:
      - "8083:8080"
    depends_on:
      - db

volumes:
  database:
  files:
