services:
  backend:
    build: ./example-backend
    image: example-backend
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
    ports:
      - "8080:8080"

  frontend:
    build: ./example-frontend
    image: example-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - HOST=0.0.0.0
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - backend
