services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  backend:
    build: ./example-backend
    image: example-backend
    restart: unless-stopped
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis

  frontend:
    build: ./example-frontend
    image: example-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - HOST=0.0.0.0
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - backend
